---
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/symlinks.yml'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/lines_in_files.yml'
- include_tasks:        '../tasks/mount_all.yml'
  when:                 lines_in_files_result.changed
